States = [
    "Maharashtra",
    "Delhi",
    "Gujarat",
    "Karnataka",
    "Tamil Nadu",
    "Uttar Pradesh",
    "Telangana",
    "West Bengal",
    "Haryana",
    "Andhra Pradesh",
    "Rajasthan",
    "Madhya Pradesh",
    "Kerala",
    "Punjab",
    "Odisha",
    "Bihar",
    "Jharkhand",
    "Chhattisgarh",
    "Assam",
    "Uttarakhand",
    "Jammu and Kashmir",
    "Goa",
    "Himachal Pradesh",
    "Puducherry",
    "Chandigarh",
    "Tripura",
    "Meghalaya",
    "Manipur",
    "Nagaland",
    "Mizoram",
    "Arunachal Pradesh",
    "Sikkim",
    "Andaman and Nicobar Islands",
    "Ladakh",
    "Daman and Diu",
    "Lakshadweep"
]

Banks = [
    "State Bank of India",
    "Punjab National Bank",
    "Bank of Baroda",
    "HDFC Bank",
    "ICICI Bank",
    "IDBI Bank Limited",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Yes Bank",
    "IDFC FIRST Bank",
    "Federal Bank",
    "RBL Bank",
    "The Varachha Co-Op Bank",
]